name: ezan_hatirlatici
description: "Prayer Times & Reminder App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.1
  flutter_localizations:
    sdk: flutter

  # Core
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.3.5
  audioplayers: ^6.5.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.2.2
  sensors_plus: ^7.0.0
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.1.5
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  animations: ^2.0.8

  # HTTP & Utils
  http: ^1.2.2
  intl: ^0.20.2
  timezone: ^0.10.1
  permission_handler: ^11.3.1

  # UI
  cupertino_icons: ^1.0.8
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/ezan.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf

# gen-l10n MUST be top-level
gen-l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  nullable-getter: false

# Flutter Gen Tools (optional)
flutter_gen:
  l10n:
    enabled: true